---
# tasks file for diodonfrost.virtio
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Include OS specific variables.
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_system }}.yml"
        - main.yml
      paths:
        - 'vars'

- name: Install Virtio
  ansible.builtin.include_tasks: "setup-{{ ansible_system }}.yml"
