---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | Virtio folder should be present
      ansible.windows.win_file:
        path: "{{ ansible_env['ProgramFiles'] }}\\virtio-win"
        state: directory
      register: virtio_path_result

    - name: Windows | Qemu-agent folder should be present
      ansible.windows.win_file:
        path: "{{ ansible_env['ProgramFiles'] }}\\qemu-ga"
        state: directory
      register: qemu_path_result

    - name: Windows | Verify commands outputs
      assert:
        that:
          - not virtio_path_result.changed
          - not qemu_path_result.changed
        success_msg: "All tests passed"
